# Generated by Django 3.0.6 on 2020-05-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postit',
            options={'verbose_name': 'Post-it Note'},
        ),
        migrations.RenameField(
            model_name='postit',
            old_name='created_date',
            new_name='creation_date',
        ),
        migrations.AlterField(
            model_name='postit',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='text',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
