# Generated by Django 3.0.6 on 2020-05-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0003_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
