# Generated by Django 3.0.6 on 2020-05-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0004_auto_20200517_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
