# Generated by Django 3.0.6 on 2020-05-17 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0006_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(blank=True, verbose_name='Notes')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation DateTime')),
                ('starred', models.BooleanField(default=False, verbose_name='Star Status')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Information Item',
                'ordering': ['title'],
            },
        ),
    ]
