# Generated by Django 3.0.6 on 2020-05-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0007_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='latest_priority_calc_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DateTime of latest Priority Recalcuation'),
        ),
        migrations.AlterField(
            model_name='action',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='information',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation DateTime'),
        ),
    ]
