# Generated by Django 3.0.6 on 2020-05-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0009_auto_20200519_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
    ]
