# Generated by Django 3.0.6 on 2020-05-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0010_auto_20200519_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='latest_priority_calc_date',
        ),
        migrations.AlterField(
            model_name='action',
            name='recreation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Recreation DateTime'),
        ),
    ]
