# Generated by Django 3.0.6 on 2020-05-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0011_auto_20200519_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='latest_priority_calc_date',
            field=models.DateTimeField(auto_now=True, verbose_name='DateTime of latest Priority Recalcuation'),
        ),
    ]
