# Generated by Django 3.0.6 on 2020-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0012_action_latest_priority_calc_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('completion_date', models.DateTimeField(auto_now_add=True, verbose_name='Completion DateTime')),
                ('effort', models.IntegerField(choices=[(1, '1 - Hardly'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Very')], verbose_name='Effort Level')),
                ('importance', models.IntegerField(choices=[(1, '1 - Hardly'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Very')], verbose_name='Importance')),
                ('enjoyment', models.IntegerField(choices=[(1, '1 - Hardly'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Very')], verbose_name='Enjoyment')),
                ('relationship', models.IntegerField(choices=[(1, '1 - Hardly'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Very')], verbose_name='Relationship')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Log',
                'ordering': ['-completion_date'],
            },
        ),
    ]
