# Generated by Django 3.0.6 on 2020-05-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0014_auto_20200520_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='Action',
            new_name='action',
        ),
    ]
