# Generated by Django 3.0.6 on 2020-05-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0015_auto_20200520_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-completion_date'], 'verbose_name': 'Completion Log'},
        ),
    ]
