# Generated by Django 3.0.6 on 2020-05-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0016_auto_20200520_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='information',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='log',
            name='tags',
        ),
    ]
