# Generated by Django 3.0.6 on 2020-05-21 17:32

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('datum', '0018_auto_20200520_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('text', models.TextField(blank=True, verbose_name='Notes')),
                ('starred', models.BooleanField(default=False, verbose_name='Star Status')),
                ('importance', models.IntegerField(choices=[(1, '1 - Hardly'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Very')], default=3, verbose_name='Importance')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TaggedWhatever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datum_taggedwhatever_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datum_taggedwhatever_items', to='datum.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='datum.TaggedWhatever', to='datum.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='information',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='datum.TaggedWhatever', to='datum.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='log',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='datum.TaggedWhatever', to='datum.Tag', verbose_name='Tags'),
        ),
    ]
