# Generated by Django 3.0.6 on 2020-05-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0019_auto_20200521_1032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='CustomTag',
        ),
    ]
