# Generated by Django 3.0.6 on 2020-05-22 17:43

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0020_auto_20200521_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='datum.TaggedWhatever', to='datum.CustomTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='information',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='datum.TaggedWhatever', to='datum.CustomTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='log',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='datum.TaggedWhatever', to='datum.CustomTag', verbose_name='Tags'),
        ),
    ]
