# Generated by Django 3.0.6 on 2020-05-30 18:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datum', '0022_auto_20200530_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='information',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Notes'),
        ),
    ]
